import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import {
  type ContainerRuntime,
  type HarnessProjectConfig,
  mergeHarnessProjectConfig,
} from "@pi-harness/shared";
import type { ExecFile } from "./exec.js";

export type PlannedFile = {
  readonly path: string;
  readonly content: string;
};

export type InitPlan =
  | {
      readonly ok: true;
      readonly config: HarnessProjectConfig;
      readonly files: ReadonlyArray<PlannedFile>;
      readonly warnings: ReadonlyArray<string>;
    }
  | {
      readonly ok: false;
      readonly error: "not_git_repo" | "no_container_runtime";
      readonly message: string;
    };

export async function createInitPlan(opts: {
  readonly cwd: string;
  readonly env: Readonly<Record<string, string | undefined>>;
  readonly execFile: ExecFile;
}): Promise<InitPlan> {
  const root = await detectGitRoot(opts.cwd, opts.execFile);
  if (!root) {
    return {
      ok: false,
      error: "not_git_repo",
      message: "pi-harness init must be run inside an existing git repository.",
    };
  }

  const runtime = await detectContainerRuntime(opts.execFile);
  if (!runtime) {
    return {
      ok: false,
      error: "no_container_runtime",
      message: "Neither podman nor docker is available on PATH.",
    };
  }

  const baseBranch = await detectBaseBranch(root, opts.execFile);
  const config = mergeHarnessProjectConfig({
    repoRoot: root,
    baseBranch,
    containerRuntime: runtime,
  });
  const files = await plannedFiles(root, config);
  return { ok: true, config, files, warnings: [] };
}

export async function applyInitPlan(root: string, plan: Extract<InitPlan, { ok: true }>): Promise<void> {
  for (const file of plan.files) {
    const fullPath = join(root, file.path);
    await mkdir(dirname(fullPath), { recursive: true });
    await writeFile(fullPath, file.content);
  }
}

export function renderHarnessConfig(config: HarnessProjectConfig): string {
  return `export default {
  repoRoot: ${JSON.stringify(config.repoRoot)},
  baseBranch: ${JSON.stringify(config.baseBranch)},
  stateDir: ${JSON.stringify(config.stateDir)},
  worktreesDir: ${JSON.stringify(config.worktreesDir)},
  containerRuntime: ${JSON.stringify(config.containerRuntime)},
  dashboardPort: ${config.dashboardPort},
  orchestratorPort: ${config.orchestratorPort},
  webProvider: ${JSON.stringify(config.webProvider)},
  graphify: {
    provider: ${JSON.stringify(config.graphify.provider)},
    model: ${JSON.stringify(config.graphify.model)},
    baseUrl: ${JSON.stringify(config.graphify.baseUrl)},
    apiKeyEnv: ${JSON.stringify(config.graphify.apiKeyEnv)},
  },
};
`;
}

export function renderComposeFile(config: HarnessProjectConfig): string {
  void config;
  return `services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: pi-harness-searxng
    ports:
      - "127.0.0.1:8888:8080"
    environment:
      SEARXNG_BASE_URL: http://localhost:8888/
      SEARXNG_SECRET: \${SEARXNG_SECRET:-pi-harness-local-searxng-change-me}
`;
}

function renderEnvHarnessExample(config: HarnessProjectConfig): string {
  return `# Required for the default phase config and Graphify provider (crofai).
CROFAI_API_KEY=

# Graphify defaults. Override these only if routing Graphify through another
# OpenAI-compatible endpoint.
GRAPHIFY_PROVIDER=${config.graphify.provider}
GRAPHIFY_MODEL=${config.graphify.model}
GRAPHIFY_BASE_URL=${config.graphify.baseUrl}
GRAPHIFY_API_KEY_ENV=${config.graphify.apiKeyEnv}

# Optional provider keys.
OPENCODE_API_KEY=
ANTHROPIC_API_KEY=
OPENAI_API_KEY=

# Web research provider for brainstorm.
PI_WEB_PROVIDER=${config.webProvider}
TINYFISH_API_KEY=

# Used only when PI_WEB_PROVIDER=searxng.
SEARXNG_URL=http://localhost:8888
SEARXNG_ALLOW_PUBLIC=false
`;
}

function renderHarnessReadme(config: HarnessProjectConfig): string {
  return `# Pi Harness Local State

This directory is generated by \`pi-harness init\` and is intentionally ignored by git.

- Worktrees: \`${relative(config.repoRoot, config.worktreesDir)}\`
- Runtime compose file: \`.harness/runtime/compose.yml\`
- Dashboard: \`http://localhost:${config.dashboardPort}\`
- Orchestrator: \`http://localhost:${config.orchestratorPort}\`
`;
}

async function plannedFiles(root: string, config: HarnessProjectConfig): Promise<ReadonlyArray<PlannedFile>> {
  return [
    { path: "harness.config.ts", content: renderHarnessConfig(config) },
    { path: ".env.harness.example", content: renderEnvHarnessExample(config) },
    { path: ".harness/runtime/compose.yml", content: renderComposeFile(config) },
    { path: ".harness/README.md", content: renderHarnessReadme(config) },
    { path: ".gitignore", content: await renderGitignore(root) },
    ...(await renderPackageJson(root)),
  ];
}

async function renderGitignore(root: string): Promise<string> {
  const path = join(root, ".gitignore");
  const current = existsSync(path) ? await readFile(path, "utf8") : "";
  if (current.split(/\r?\n/).includes(".harness/")) return current;
  const separator = current.length > 0 && !current.endsWith("\n") ? "\n" : "";
  return `${current}${separator}.harness/\n`;
}

async function renderPackageJson(root: string): Promise<ReadonlyArray<PlannedFile>> {
  const path = join(root, "package.json");
  if (!existsSync(path)) return [];
  const parsed = parseJsonObject(await readFile(path, "utf8"));
  if (!parsed) return [];
  const scripts = parseJsonObject(parsed["scripts"]);
  const next = {
    ...parsed,
    scripts: {
      ...scripts,
      "pi-harness": "pi-harness",
    },
  };
  return [{ path: "package.json", content: `${JSON.stringify(next, null, 2)}\n` }];
}

function parseJsonObject(value: unknown): Record<string, unknown> | null {
  if (typeof value === "string") {
    try {
      return parseJsonObject(JSON.parse(value));
    } catch {
      return null;
    }
  }
  if (typeof value !== "object" || value === null || Array.isArray(value)) return null;
  return Object.fromEntries(Object.entries(value));
}

async function detectGitRoot(cwd: string, execFile: ExecFile): Promise<string | null> {
  const result = await execFile("git", ["rev-parse", "--show-toplevel"], { cwd });
  return result.ok ? result.stdout.trim() : null;
}

async function detectBaseBranch(root: string, execFile: ExecFile): Promise<string> {
  const current = await execFile("git", ["branch", "--show-current"], { cwd: root });
  if (current.ok && current.stdout.trim()) return current.stdout.trim();
  const symbolic = await execFile("git", ["symbolic-ref", "refs/remotes/origin/HEAD"], { cwd: root });
  if (!symbolic.ok) return "main";
  return symbolic.stdout.trim().replace(/^refs\/remotes\/origin\//, "") || "main";
}

async function detectContainerRuntime(execFile: ExecFile): Promise<ContainerRuntime | null> {
  const podman = await execFile("podman", ["--version"]);
  if (podman.ok) return "podman";
  const docker = await execFile("docker", ["--version"]);
  if (docker.ok) return "docker";
  return null;
}
